[package]
edition = "2021"
name = "instrument_fib"
publish = false
version = "0.1.0"

[dependencies]
crustrace.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
