[package]
edition = "2021"
name = "fib"
version = "0.1.0"

[dependencies]
crustrace = { path = "../../crustrace" }
tracing = { version = "0.1.41", default-features = false, features = [
  "attributes",
] }
tracing-subscriber = "0.3"
