[package]
edition = "2021"
name = "fib"
version = "0.1.0"

[dependencies]
crustrace = { path = "../../crustrace" }
tracing = { default-features = false, features = [
  "attributes",
], version = "0.1.41" }
tracing-subscriber = "0.3"
