[package]
edition = "2021"
name = "omni_fib_struct"
publish = false
version = "0.1.0"

[dependencies]
crustrace.workspace = true
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
